package com.example.reminder.domain.enums;

public enum ActivityLogType {
    NOTIFICATION_RECEIVED,
    ALERT_RECEIVED,
    CHECKED_IN,
    CHECK_IN_SNOOZED,
    HELP_REQUESTED,
    SOS_SENT,
    DAILY_CHECK_IN_TIME_UPDATED,
    REMINDER_CREATED,
    SCHEDULE_CREATED,
    ESCALATION_TRIGGERED,
    SAFETY_ALERT_SENT,
    PAYMENT_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    SUBSCRIPTION_PURCHASED,
    SUBSCRIPTION_UPGRADED,
    SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_EXPIRED
}
