package com.example.reminder.exception;

public enum DecryptDenyReason {
    ASSET_NOT_FOUND,
    CONTACT_ACCESS_MISMATCH,
    CONTACT_INACTIVE,
    ACTOR_MISMATCH,
    NOT_UNLOCKED,
    DELAY_NOT_ELAPSED,
    POLICY_USER_INACTIVE,
    POLICY_MULTIPLE_CONTACTS,
    INVALID_POLICY,
    TOKEN_INVALID,
    TOKEN_CONTEXT_MISMATCH,
    RATE_LIMITED,
    UNKNOWN
}
